-- Firebird migration: rebuild tables so EMPLOYEE_ID uses BIGINT.
-- Safe for the current ATTENDANCE.FDB state and preserves existing data.

CREATE TABLE TMP_EMPLOYEES_BIGINT (
    EMPLOYEE_ID BIGINT,
    NAME VARCHAR(255),
    ROLE VARCHAR(100),
    PICTURE BLOB SUB_TYPE TEXT,
    STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP
);

CREATE TABLE TMP_ADMINS_BIGINT (
    ADMIN_ID INTEGER,
    EMPLOYEE_ID BIGINT,
    CREATED_AT TIMESTAMP
);

CREATE TABLE TMP_ADMIN_CREDENTIALS_BIGINT (
    CREDENTIAL_ID INTEGER,
    EMPLOYEE_ID BIGINT,
    PASSWORD_HASH VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE TMP_ATTENDANCE_LOGS_BIGINT (
    LOG_ID INTEGER,
    EMPLOYEE_ID BIGINT,
    TIME_IN TIMESTAMP,
    TIME_OUT TIMESTAMP,
    DATE_LOG DATE,
    STATUS VARCHAR(20),
    LOCATION VARCHAR(20),
    SITE VARCHAR(100),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

INSERT INTO TMP_EMPLOYEES_BIGINT (EMPLOYEE_ID, NAME, ROLE, PICTURE, STATUS, CREATED_AT)
SELECT EMPLOYEE_ID, NAME, ROLE, PICTURE, STATUS, CREATED_AT
FROM EMPLOYEES;

INSERT INTO TMP_ADMINS_BIGINT (ADMIN_ID, EMPLOYEE_ID, CREATED_AT)
SELECT ADMIN_ID, EMPLOYEE_ID, CREATED_AT
FROM ADMINS;

INSERT INTO TMP_ADMIN_CREDENTIALS_BIGINT (CREDENTIAL_ID, EMPLOYEE_ID, PASSWORD_HASH, CREATED_AT, UPDATED_AT)
SELECT CREDENTIAL_ID, EMPLOYEE_ID, PASSWORD_HASH, CREATED_AT, UPDATED_AT
FROM ADMIN_CREDENTIALS;

INSERT INTO TMP_ATTENDANCE_LOGS_BIGINT (LOG_ID, EMPLOYEE_ID, TIME_IN, TIME_OUT, DATE_LOG, STATUS, LOCATION, SITE, CREATED_AT, UPDATED_AT)
SELECT LOG_ID, EMPLOYEE_ID, TIME_IN, TIME_OUT, DATE_LOG, STATUS, LOCATION, SITE, CREATED_AT, UPDATED_AT
FROM ATTENDANCE_LOGS;

COMMIT;

DROP TABLE ADMIN_CREDENTIALS;
DROP TABLE ADMINS;
DROP TABLE ATTENDANCE_LOGS;
DROP TABLE EMPLOYEES;

COMMIT;

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    ROLE VARCHAR(100),
    PICTURE BLOB SUB_TYPE TEXT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ADMINS (
    ADMIN_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE ADMIN_CREDENTIALS (
    CREDENTIAL_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE ATTENDANCE_LOGS (
    LOG_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID BIGINT NOT NULL,
    TIME_IN TIMESTAMP,
    TIME_OUT TIMESTAMP,
    DATE_LOG DATE NOT NULL,
    STATUS VARCHAR(20),
    LOCATION VARCHAR(20),
    SITE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, NAME, ROLE, PICTURE, STATUS, CREATED_AT)
SELECT EMPLOYEE_ID, NAME, ROLE, PICTURE, COALESCE(STATUS, 'ACTIVE'), CREATED_AT
FROM TMP_EMPLOYEES_BIGINT;

INSERT INTO ADMINS (ADMIN_ID, EMPLOYEE_ID, CREATED_AT)
SELECT ADMIN_ID, EMPLOYEE_ID, CREATED_AT
FROM TMP_ADMINS_BIGINT;

INSERT INTO ADMIN_CREDENTIALS (CREDENTIAL_ID, EMPLOYEE_ID, PASSWORD_HASH, CREATED_AT, UPDATED_AT)
SELECT CREDENTIAL_ID, EMPLOYEE_ID, PASSWORD_HASH, CREATED_AT, UPDATED_AT
FROM TMP_ADMIN_CREDENTIALS_BIGINT;

INSERT INTO ATTENDANCE_LOGS (LOG_ID, EMPLOYEE_ID, TIME_IN, TIME_OUT, DATE_LOG, STATUS, LOCATION, SITE, CREATED_AT, UPDATED_AT)
SELECT LOG_ID, EMPLOYEE_ID, TIME_IN, TIME_OUT, DATE_LOG, STATUS, LOCATION, SITE, CREATED_AT, UPDATED_AT
FROM TMP_ATTENDANCE_LOGS_BIGINT;

COMMIT;

DROP TABLE TMP_ADMIN_CREDENTIALS_BIGINT;
DROP TABLE TMP_ADMINS_BIGINT;
DROP TABLE TMP_ATTENDANCE_LOGS_BIGINT;
DROP TABLE TMP_EMPLOYEES_BIGINT;

COMMIT;