-- Attendance System Database Schema for Firebird
-- Platform: Firebird 5.0 SuperServer
-- Purpose: Admin panel + Kiosk app shared database

-- EMPLOYEES Table: Core employee data
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255),
    ROLE VARCHAR(100),
    PICTURE BLOB SUB_TYPE TEXT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ADMINS Table: Links employees who are admins
CREATE TABLE ADMINS (
    ADMIN_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID INTEGER NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- ADMIN_CREDENTIALS Table: Stores admin passwords for authentication
CREATE TABLE ADMIN_CREDENTIALS (
    CREDENTIAL_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID INTEGER NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- ATTENDANCE_LOGS Table: Daily time tracking
CREATE TABLE ATTENDANCE_LOGS (
    LOG_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID INTEGER NOT NULL,
    TIME_IN TIMESTAMP,
    TIME_OUT TIMESTAMP,
    DATE_LOG DATE NOT NULL,
    STATUS VARCHAR(20),
    LOCATION VARCHAR(20),    -- 'OFFICE' or 'ONSITE'
    SITE VARCHAR(100),       -- site name for onsite service
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
